# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/pyramid/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/pyramid/proprietary/lib/hw/vendor-camera.msm8660.so:obj/lib/vendor-camera.msm8660.so \
    vendor/htc/pyramid/proprietary/lib/libacdbmapper.so:obj/lib/libacdbmapper.so

PRODUCT_COPY_FILES += \
        vendor/htc/pyramid/proprietary/bin/ipd:system/bin/ipd \
        vendor/htc/pyramid/proprietary/bin/netsharing:system/bin/netsharing \
        vendor/htc/pyramid/proprietary/etc/agps_rm:system/etc/agps_rm \
        vendor/htc/pyramid/proprietary/etc/vpimg:system/etc/vpimg \
        vendor/htc/pyramid/proprietary/lib/hw/sensors.pyramid.so:system/lib/hw/sensors.pyramid.so \
        vendor/htc/pyramid/proprietary/lib/libchromatix_s5k3h1gx_default_video.so:system/lib/libchromatix_s5k3h1gx_default_video.so \
        vendor/htc/pyramid/proprietary/lib/libchromatix_s5k3h1gx_hfr.so:system/lib/libchromatix_s5k3h1gx_hfr.so \
        vendor/htc/pyramid/proprietary/lib/libchromatix_s5k3h1gx_preview.so:system/lib/libchromatix_s5k3h1gx_preview.so \
        vendor/htc/pyramid/proprietary/lib/libchromatix_s5k3h1gx_zsl.so:system/lib/libchromatix_s5k3h1gx_zsl.so \
        vendor/htc/pyramid/proprietary/lib/libmpl_jni.so:system/lib/libmpl_jni.so \
        vendor/htc/pyramid/proprietary/bin/charging:/system/bin/charging \
        vendor/htc/pyramid/proprietary/bin/htcbatt:/system/bin/htcbatt \
        vendor/htc/pyramid/proprietary/bin/netmgrd:/system/bin/netmgrd \
        vendor/htc/pyramid/proprietary/lib/hw/vendor-camera.msm8660.so:/system/lib/hw/vendor-camera.msm8660.so \
        vendor/htc/pyramid/proprietary/lib/libacdbmapper.so:/system/lib/libacdbmapper.so \
        vendor/htc/pyramid/proprietary/lib/libaudcal.so:/system/lib/libaudcal.so \
        vendor/htc/pyramid/proprietary/lib/libgemini.so:/system/lib/libgemini.so \
        vendor/htc/pyramid/proprietary/lib/libhtc_ril.so:/system/lib/libhtc_ril.so \
        vendor/htc/pyramid/proprietary/lib/libmllite.so:/system/lib/libmllite.so \
        vendor/htc/pyramid/proprietary/lib/libmmipl.so:/system/lib/libmmipl.so \
        vendor/htc/pyramid/proprietary/lib/libmmjpeg.so:/system/lib/libmmjpeg.so \
        vendor/htc/pyramid/proprietary/lib/liboemcamera.so:/system/lib/liboemcamera.so \
        vendor/htc/pyramid/proprietary/lib/libOlaEngine.so:/system/lib/libOlaEngine.so \
        vendor/htc/pyramid/proprietary/lib/libposteffect.so:/system/lib/libposteffect.so \
        vendor/htc/pyramid/proprietary/lib/libqdp.so:/system/lib/libqdp.so
