# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/shooter/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/shooter/proprietary/system/lib/hw/vendor-camera.default.so:obj/lib/hw/vendor-camera.default.so \
    vendor/htc/shooter/proprietary/system/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/htc/shooter/proprietary/system/lib/libacdbloader.so:obj/lib/libacdbloader.so \
    vendor/htc/shooter/proprietary/system/lib/libacdbmapper.so:obj/lib/libacdbmapper.so

PRODUCT_PROPERTY_OVERRIDES += \
     drm.service.enabled=true

PRODUCT_COPY_FILES += \
  vendor/htc/shooter/proprietary/system/bin/3D_calibration:bin/3D_calibration \
  vendor/htc/shooter/proprietary/system/bin/3D_calibration_main:bin/3D_calibration_main \
  vendor/htc/shooter/proprietary/system/bin/charging:bin/charging \
  vendor/htc/shooter/proprietary/system/bin/dmagent:bin/dmagent \
  vendor/htc/shooter/proprietary/system/bin/getWiMAXPropDaemond:bin/getWiMAXPropDaemond \
  vendor/htc/shooter/proprietary/system/bin/htcbatt:bin/htcbatt \
  vendor/htc/shooter/proprietary/system/bin/load-modem.sh:bin/load-modem.sh \
  vendor/htc/shooter/proprietary/system/bin/logcat2:bin/logcat2 \
  vendor/htc/shooter/proprietary/system/bin/netmgrd:bin/netmgrd \
  vendor/htc/shooter/proprietary/system/bin/qmuxd:bin/qmuxd \
  vendor/htc/shooter/proprietary/system/bin/rmt_storage:bin/rmt_storage \
  vendor/htc/shooter/proprietary/system/bin/sequansd:bin/sequansd \
  vendor/htc/shooter/proprietary/system/bin/setWiMAXPropDaemond:bin/setWiMAXPropDaemond \
  vendor/htc/shooter/proprietary/system/bin/sound8x60:bin/sound8x60 \
  vendor/htc/shooter/proprietary/system/bin/wimax_mtd:bin/wimax_mtd \
  vendor/htc/shooter/proprietary/system/bin/wimaxAddRoute:bin/wimaxAddRoute \
  vendor/htc/shooter/proprietary/system/bin/wimaxConfigInterface:bin/wimaxConfigInterface \
  vendor/htc/shooter/proprietary/system/bin/wimaxDaemon:bin/wimaxDaemon \
  vendor/htc/shooter/proprietary/system/bin/wimaxDhcpRelease:bin/wimaxDhcpRelease \
  vendor/htc/shooter/proprietary/system/bin/wimaxDhcpRenew:bin/wimaxDhcpRenew \
  vendor/htc/shooter/proprietary/system/bin/wimaxDumpKmsg:bin/wimaxDumpKmsg \
  vendor/htc/shooter/proprietary/system/bin/wimaxDumpLastKmsg:bin/wimaxDumpLastKmsg \
  vendor/htc/shooter/proprietary/system/bin/wimaxDumpLogcat:bin/wimaxDumpLogcat \
  vendor/htc/shooter/proprietary/system/bin/wimaxFactoryReset:bin/wimaxFactoryReset \
  vendor/htc/shooter/proprietary/system/bin/wireless_modem:bin/wireless_modem \
  vendor/htc/shooter/proprietary/system/etc/permissions/com.google.widevine.software.drm.xml:etc/permissions/com.google.widevine.software.drm.xml \
  vendor/htc/shooter/proprietary/system/etc/wimax/dhcp/wimaxDhcp.conf:etc/wimax/dhcp/wimaxDhcp.conf \
  vendor/htc/shooter/proprietary/system/etc/wimax/sequansd/DefaultTree.xml:etc/wimax/sequansd/DefaultTree.xml \
  vendor/htc/shooter/proprietary/system/etc/wimax/sequansd/sequansd_app.xml:etc/wimax/sequansd/sequansd_app.xml \
  vendor/htc/shooter/proprietary/system/framework/com.google.widevine.software.drm.jar:framework/com.google.widevine.software.drm.jar \
  vendor/htc/shooter/proprietary/system/framework/wimax-api.jar:framework/wimax-api.jar \
  vendor/htc/shooter/proprietary/system/lib/egl/eglsubAndroid.so:lib/egl/eglsubAndroid.so \
  vendor/htc/shooter/proprietary/system/lib/egl/libEGL_adreno200.so:lib/egl/libEGL_adreno200.so \
  vendor/htc/shooter/proprietary/system/lib/egl/libGLESv1_CM_adreno200.so:lib/egl/libGLESv1_CM_adreno200.so \
  vendor/htc/shooter/proprietary/system/lib/egl/libGLESv2_adreno200.so:lib/egl/libGLESv2_adreno200.so \
  vendor/htc/shooter/proprietary/system/lib/egl/libGLESv2S3D_adreno200.so:lib/egl/libGLESv2S3D_adreno200.so \
  vendor/htc/shooter/proprietary/system/lib/egl/libq3dtools_adreno200.so:lib/egl/libq3dtools_adreno200.so \
  vendor/htc/shooter/proprietary/system/lib/hw/sensors.shooter.so:lib/hw/sensors.shooter.so \
  vendor/htc/shooter/proprietary/system/lib/hw/vendor-camera.default.so:lib/hw/vendor-camera.default.so \
  vendor/htc/shooter/proprietary/system/lib/libacdbloader.so:lib/libacdbloader.so \
  vendor/htc/shooter/proprietary/system/lib/libacdbmapper.so:lib/libacdbmapper.so \
  vendor/htc/shooter/proprietary/system/lib/libaudcal.so:lib/libaudcal.so \
  vendor/htc/shooter/proprietary/system/lib/libaudioalsa.so:lib/libaudioalsa.so \
  vendor/htc/shooter/proprietary/system/lib/libC2D2.so:lib/libC2D2.so \
  vendor/htc/shooter/proprietary/system/lib/libc2d2_z180.so:lib/libc2d2_z180.so \
  vendor/htc/shooter/proprietary/system/lib/libcameraface.so:lib/libcameraface.so \
  vendor/htc/shooter/proprietary/system/lib/libcamerapp.so:lib/libcamerapp.so \
  vendor/htc/shooter/proprietary/system/lib/libcameraSP.so:lib/libcameraSP.so \
  vendor/htc/shooter/proprietary/system/lib/libcryp98.so:lib/libcryp98.so \
  vendor/htc/shooter/proprietary/system/lib/libdiag.so:lib/libdiag.so \
  vendor/htc/shooter/proprietary/system/lib/libdll.so:lib/libdll.so \
  vendor/htc/shooter/proprietary/system/lib/libdmtree.so:lib/libdmtree.so \
  vendor/htc/shooter/proprietary/system/lib/libdsi_netctrl.so:lib/libdsi_netctrl.so \
  vendor/htc/shooter/proprietary/system/lib/libdsutils.so:lib/libdsutils.so \
  vendor/htc/shooter/proprietary/system/lib/libfrsdk.so:lib/libfrsdk.so \
  vendor/htc/shooter/proprietary/system/lib/libgemini.so:lib/libgemini.so \
  vendor/htc/shooter/proprietary/system/lib/libgemini2.so:lib/libgemini2.so \
  vendor/htc/shooter/proprietary/system/lib/libgsl.so:lib/libgsl.so \
  vendor/htc/shooter/proprietary/system/lib/libhtc_acoustic.so:lib/libhtc_acoustic.so \
  vendor/htc/shooter/proprietary/system/lib/libhtc_ril.so:lib/libhtc_ril.so \
  vendor/htc/shooter/proprietary/system/lib/libhtc_ril_switch.so:lib/libhtc_ril_switch.so \
  vendor/htc/shooter/proprietary/system/lib/libhtcdm.so:lib/libhtcdm.so \
  vendor/htc/shooter/proprietary/system/lib/libidl.so:lib/libidl.so \
  vendor/htc/shooter/proprietary/system/lib/libmllite.so:lib/libmllite.so \
  vendor/htc/shooter/proprietary/system/lib/libmlplatform.so:lib/libmlplatform.so \
  vendor/htc/shooter/proprietary/system/lib/libmm-color-convertor.so:lib/libmm-color-convertor.so \
  vendor/htc/shooter/proprietary/system/lib/libmmipl.so:lib/libmmipl.so \
  vendor/htc/shooter/proprietary/system/lib/libmmjpeg.so:lib/libmmjpeg.so \
  vendor/htc/shooter/proprietary/system/lib/libmmjpeg2.so:lib/libmmjpeg2.so \
  vendor/htc/shooter/proprietary/system/lib/libmmjps.so:lib/libmmjps.so \
  vendor/htc/shooter/proprietary/system/lib/libmmmpo.so:lib/libmmmpo.so \
  vendor/htc/shooter/proprietary/system/lib/libmpl.so:lib/libmpl.so \
  vendor/htc/shooter/proprietary/system/lib/libnetmgr.so:lib/libnetmgr.so \
  vendor/htc/shooter/proprietary/system/lib/liboemcamera.so:lib/liboemcamera.so \
  vendor/htc/shooter/proprietary/system/lib/libOlaEngine.so:lib/libOlaEngine.so \
  vendor/htc/shooter/proprietary/system/lib/libOpenVG.so:lib/libOpenVG.so \
  vendor/htc/shooter/proprietary/system/lib/libposteffect.so:lib/libposteffect.so \
  vendor/htc/shooter/proprietary/system/lib/libqc-opt.so:lib/libqc-opt.so \
  vendor/htc/shooter/proprietary/system/lib/libqdp.so:lib/libqdp.so \
  vendor/htc/shooter/proprietary/system/lib/libqmi.so:lib/libqmi.so \
  vendor/htc/shooter/proprietary/system/lib/libqmiservices.so:lib/libqmiservices.so \
  vendor/htc/shooter/proprietary/system/lib/libsc-a2xx.so:lib/libsc-a2xx.so \
  vendor/htc/shooter/proprietary/system/lib/libWVphoneAPI.so:lib/libWVphoneAPI.so \
  vendor/htc/shooter/proprietary/system/vendor/lib/drm/libdrmwvmplugin.so:vendor/lib/drm/libdrmwvmplugin.so \
  vendor/htc/shooter/proprietary/system/vendor/lib/libwvdrm_L1.so:vendor/lib/libwvdrm_L1.so \
  vendor/htc/shooter/proprietary/system/vendor/lib/libwvm.so:vendor/lib/libwvm.so \
  vendor/htc/shooter/proprietary/system/vendor/lib/libWVStreamControlAPI_L1.so:vendor/lib/libWVStreamControlAPI_L1.so \
  vendor/htc/shooter/proprietary/system/xbin/wireless_modem:xbin/wireless_modem
