# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/shooterk/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/shooterk/proprietary/lib/hw/vendor-camera.msm8660.so:obj/lib/vendor-camera.msm8660.so \
    vendor/htc/shooterk/proprietary/lib/libacdbmapper.so:obj/lib/libacdbmapper.so

PRODUCT_COPY_FILES += \
        vendor/htc/shooterk/proprietary/bin/3D_calibration:/system/bin/3D_calibration \
        vendor/htc/shooterk/proprietary/bin/3D_calibration_main:/system/bin/3D_calibration_main \
        vendor/htc/shooterk/proprietary/bin/dmagent:/system/bin/dmagent \
        vendor/htc/shooterk/proprietary/bin/getWiMAXPropDaemond:/system/bin/getWiMAXPropDaemond \
        vendor/htc/shooterk/proprietary/bin/load-modem.sh:/system/bin/load-modem.sh \
        vendor/htc/shooterk/proprietary/bin/logcat2:/system/bin/logcat2 \
        vendor/htc/shooterk/proprietary/bin/sequansd:/system/bin/sequansd \
        vendor/htc/shooterk/proprietary/bin/setWiMAXPropDaemond:/system/bin/setWiMAXPropDaemond \
        vendor/htc/shooterk/proprietary/bin/sound8x60:/system/bin/sound8x60 \
        vendor/htc/shooterk/proprietary/bin/wimax_mtd:/system/bin/wimax_mtd \
        vendor/htc/shooterk/proprietary/bin/wimaxAddRoute:/system/bin/wimaxAddRoute \
        vendor/htc/shooterk/proprietary/bin/wimaxConfigInterface:/system/bin/wimaxConfigInterface \
        vendor/htc/shooterk/proprietary/bin/wimaxDaemon:/system/bin/wimaxDaemon \
        vendor/htc/shooterk/proprietary/bin/wimaxDhcpRelease:/system/bin/wimaxDhcpRelease \
        vendor/htc/shooterk/proprietary/bin/wimaxDhcpRenew:/system/bin/wimaxDhcpRenew \
        vendor/htc/shooterk/proprietary/bin/wimaxDumpKmsg:/system/bin/wimaxDumpKmsg \
        vendor/htc/shooterk/proprietary/bin/wimaxDumpLastKmsg:/system/bin/wimaxDumpLastKmsg \
        vendor/htc/shooterk/proprietary/bin/wimaxDumpLogcat:/system/bin/wimaxDumpLogcat \
        vendor/htc/shooterk/proprietary/bin/wimaxFactoryReset:/system/bin/wimaxFactoryReset \
        vendor/htc/shooterk/proprietary/bin/wireless_modem:/system/bin/wireless_modem \
        vendor/htc/shooterk/proprietary/etc/wimax/dhcp/wimaxDhcp.conf:/system/etc/wimax/dhcp/wimaxDhcp.conf \
        vendor/htc/shooterk/proprietary/etc/wimax/sequansd/DefaultTree.xml:/system/etc/wimax/sequansd/DefaultTree.xml \
        vendor/htc/shooterk/proprietary/etc/wimax/sequansd/sequansd_app.xml:/system/etc/wimax/sequansd/sequansd_app.xml \
        vendor/htc/shooterk/proprietary/framework/wimax-api.jar:/system/framework/wimax-api.jar \
        vendor/htc/shooterk/proprietary/lib/hw/sensors.shooterk.so:/system/lib/hw/sensors.shooterk.so \
        vendor/htc/shooterk/proprietary/lib/libcryp98.so:/system/lib/libcryp98.so \
        vendor/htc/shooterk/proprietary/lib/libdmtree.so:/system/lib/libdmtree.so \
        vendor/htc/shooterk/proprietary/lib/libfrsdk.so:/system/lib/libfrsdk.so \
        vendor/htc/shooterk/proprietary/lib/libgemini2.so:/system/lib/libgemini2.so \
        vendor/htc/shooterk/proprietary/lib/libhtc_ril_switch.so:/system/lib/libhtc_ril_switch.so \
        vendor/htc/shooterk/proprietary/lib/libhtcdm.so:/system/lib/libhtcdm.so \
        vendor/htc/shooterk/proprietary/lib/libmmjpeg2.so:/system/lib/libmmjpeg2.so \
        vendor/htc/shooterk/proprietary/lib/libmmjps.so:/system/lib/libmmjps.so \
        vendor/htc/shooterk/proprietary/lib/libmmmpo.so:/system/lib/libmmmpo.so \
        vendor/htc/shooterk/proprietary/lib/libqc-opt.so:/system/lib/libqc-opt.so \
        vendor/htc/shooterk/proprietary/xbin/wireless_modem:/system/xbin/wireless_modem \
        vendor/htc/shooterk/proprietary/bin/charging:/system/bin/charging \
        vendor/htc/shooterk/proprietary/bin/htcbatt:/system/bin/htcbatt \
        vendor/htc/shooterk/proprietary/bin/netmgrd:/system/bin/netmgrd \
        vendor/htc/shooterk/proprietary/lib/hw/vendor-camera.msm8660.so:/system/lib/hw/vendor-camera.msm8660.so \
        vendor/htc/shooterk/proprietary/lib/libacdbmapper.so:/system/lib/libacdbmapper.so \
        vendor/htc/shooterk/proprietary/lib/libaudcal.so:/system/lib/libaudcal.so \
        vendor/htc/shooterk/proprietary/lib/libgemini.so:/system/lib/libgemini.so \
        vendor/htc/shooterk/proprietary/lib/libhtc_ril.so:/system/lib/libhtc_ril.so \
        vendor/htc/shooterk/proprietary/lib/libmllite.so:/system/lib/libmllite.so \
        vendor/htc/shooterk/proprietary/lib/libmmipl.so:/system/lib/libmmipl.so \
        vendor/htc/shooterk/proprietary/lib/libmmjpeg.so:/system/lib/libmmjpeg.so \
        vendor/htc/shooterk/proprietary/lib/liboemcamera.so:/system/lib/liboemcamera.so \
        vendor/htc/shooterk/proprietary/lib/libOlaEngine.so:/system/lib/libOlaEngine.so \
        vendor/htc/shooterk/proprietary/lib/libposteffect.so:/system/lib/libposteffect.so \
        vendor/htc/shooterk/proprietary/lib/libqdp.so:/system/lib/libqdp.so
