# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/holiday/setup-makefiles.sh
PRODUCT_COPY_FILES += \
  vendor/htc/shooter/proprietary/lib/hw/vendor-camera.default.so:obj/lib/vendor-camera.default.so \
  vendor/htc/holiday/proprietary/lib/libacdbmapper.so:obj/lib/libacdbmapper.so

PRODUCT_COPY_FILES += \
        vendor/htc/holiday/proprietary/bin/awb_camera:/system/bin/awb_camera \
        vendor/htc/holiday/proprietary/bin/bma150_usr:/system/bin/bma 150_usr \
        vendor/htc/holiday/proprietary/bin/dmagent:/system/bin/dmagent \
        vendor/htc/holiday/proprietary/bin/ip:/system/bin/ip \
        vendor/htc/holiday/proprietary/bin/ks:/system/bin/ks \
        vendor/htc/holiday/proprietary/bin/mm-abl-daemon:/system/bin/mm-abl-daemon \
        vendor/htc/holiday/proprietary/bin/netsharing:/system/bin/netsharing \
        vendor/htc/holiday/proprietary/bin/qcks:/system/bin/qcks \
        vendor/htc/holiday/proprietary/bin/qmiproxy:/system/bin/qmiproxy \
        vendor/htc/holiday/proprietary/bin/wireless_modem:/system/bin/wireless_modem \
        vendor/htc/holiday/proprietary/bin/zchgd:/system/bin/zchgd \
        vendor/htc/holiday/proprietary/etc/vpimg:/system/etc/vpimg \
        vendor/htc/holiday/proprietary/lib/hw/sensors.holiday.so:/system/lib/hw/sensors.holiday.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_imx105_default_video.so:/system/lib/libchromatix_imx105_default_video.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_imx105_preview.so:/system/lib/libchromatix_imx105_preview.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_imx105_zsl.so:/system/lib/libchromatix_imx105_zsl.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_mt9d015_default_video.so:/system/lib/libchromatix_mt9d015_default_video.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_mt9d015_default_zsl.so:/system/lib/libchromatix_mt9d015_default_zsl.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_mt9d015_preview.so:/system/lib/libchromatix_mt9d015_preview.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_ov8830_default_video.so:/system/lib/libchromatix_ov8830_default_video.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_ov8830_hfr.so:/system/lib/libchromatix_ov8830_hfr.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_ov8830_preview.so:/system/libchromatix_ov8830_preview.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_ov8830_zsl.so:/system/lib/libchromatix_ov8830_zsl.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_s5k3h1gx_default_video.so:/system/lib/libchromatix_s5k3h1gx_default_video.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_s5k3h1gx_hfr.so:/system/lib/libchromatix_s5k3h1gx_hfr.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_s5k3h1gx_preview.so:/system/lib/libchromatix_s5k3h1gx_preview.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_s5k3h1gx_zsl.so:/system/lib/libchromatix_s5k3h1gx_zsl.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_s5k3h2yx_default_video.so:/system/lib/libchromatix_s5k3h2yx_default_video.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_s5k3h2yx_hfr.so:/system/lib/libchromatix_s5k3h2yx_hfr.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_s5k3h2yx_preview.so:/system/lib/libchromatix_s5k3h2yx_preview.so \
        vendor/htc/holiday/proprietary/lib/libchromatix_s5k3h2yx_zsl.so:/system/lib/libchromatix_s5k3h2yx_zsl.so \
        vendor/htc/holiday/proprietary/lib/libdsm.so:/system/lib/libdsm.so \
        vendor/htc/holiday/proprietary/lib/libmpl_jni.so:/system/lib/libmpl_jni.so \
        vendor/htc/holiday/proprietary/lib/libnv.so:/system/lib/libnv.so \
        vendor/htc/holiday/proprietary/lib/liboncrpc.so:/system/lib/liboncrpc.so \
        vendor/htc/holiday/proprietary/lib/libpbmlib.so:/system/lib/libpbmlib.so \
        vendor/htc/holiday/proprietary/lib/libqc-opt.so:/system/lib/libqc-opt.so \
        vendor/htc/holiday/proprietary/lib/libqueue.so:/system/lib/libqueue.so \
        vendor/htc/holiday/proprietary/lib/libril.so:/system/lib/libril.so \
        vendor/htc/holiday/proprietary/lib/libril-qc-qmi-1.so:/system/lib/libril-qc-qmi-1.so \
        vendor/htc/holiday/proprietary/lib/libril-qcril-hook-oem.so:/system/lib/libril-qcril-hook-oem.so \
        vendor/htc/holiday/proprietary/bin/charging:/system/bin/charging \
        vendor/htc/holiday/proprietary/bin/charging:/system/bin/charging \
        vendor/htc/holiday/proprietary/bin/htcbatt:/system/bin/htcbatt \
        vendor/htc/holiday/proprietary/bin/netmgrd:/system/bin/netmgrd \
        vendor/htc/holiday/proprietary/lib/hw/vendor-camera.default.so:/system/lib/hw/vendor-camera.default.so \
        vendor/htc/holiday/proprietary/lib/libacdbmapper.so:/system/lib/libacdbmapper.so \
        vendor/htc/holiday/proprietary/lib/libaudcal.so:/system/lib/libaudcal.so \
        vendor/htc/holiday/proprietary/lib/libgemini.so:/system/lib/libgemini.so \
        vendor/htc/holiday/proprietary/lib/libmllite.so:/system/lib/libmllite.so \
        vendor/htc/holiday/proprietary/lib/libmmipl.so:/system/lib/libmmipl.so \
        vendor/htc/holiday/proprietary/lib/libmmjpeg.so:/system/lib/libmmjpeg.so \
        vendor/htc/holiday/proprietary/lib/liboemcamera.so:/system/lib/liboemcamera.so \
        vendor/htc/holiday/proprietary/lib/libOlaEngine.so:/system/lib/libOlaEngine.so \
        vendor/htc/holiday/proprietary/lib/libposteffect.so:/system/lib/libposteffect.so \
        vendor/htc/holiday/proprietary/lib/libqdp.so:/system/lib/libqdp.so
